In [ ]:
import pandas as pd

In [ ]:
# 파일 로드 
corona = pd.read_csv("../../csv/corona.csv")
# 특정 컬럼을 제거 (Unnamed: 0, seq)
corona.drop( ['Unnamed: 0', 'seq'], axis=1, inplace=True )
# 컬럼의 이름을 변경 
corona.columns = ["등록일시", '총사망자', '총확진자', '기준일', 
                  '기준시간', '수정일시', '누적의심자', '누적확진율']
# 복사본 생성
df = corona.copy()
# 등록일시를 기준으로 오름차순 정렬
df.sort_values( ['등록일시'], inplace=True )
# 인덱스를 초기화하고 기존의 인덱스는 제거 
df.reset_index(drop = True, inplace=True)

In [ ]:
df.head()

In [ ]:
# 파생변수 생성 
# 반복문을 이용하여 일일사망자 컬럼을 추가 
datas = [0]

for i in range(1, len(df), 1):
    # 오늘의 인덱스의 총 사망자 - 전날의 인덱스의 총사망자 
    data = df.loc[i, '총사망자'] - df.loc[i-1, '총사망자']
    datas.append(data)

df['일일사망자'] = datas

In [ ]:
df.head()

In [12]:
# shift() 함수 이용
# shift(n) : 특정 Series데이터에서 n만큼 인덱스의 위치를 이동
df['일일사망자2'] = (df['총사망자'] - df['총사망자'].shift()).fillna(0)

In [15]:
# diff() 함수 이용
# diff(n) : 특정 Seried 데이터에서 n만큼 인덱스의 위치를 이동한 값과의 차이를 출력
# n은 1이 기본값
df['일일사망자3'] = df['총사망자'].diff().fillna(0)

In [ ]:
df.head()

In [ ]:
# 데이터프레임에서 마지막 3개의 컬럼만 추출
# 위치에서 음수가 의미하는것은?
df.iloc[ : , -3: ]

In [20]:
(df['일일사망자'] == df['일일사망자2']).sum()

820

In [22]:
(df['일일사망자'] == df['일일사망자3']).value_counts()

True    820
Name: count, dtype: int64

In [23]:
# 통계 요약 정보를 출력하는 함수 
# describe()
df.describe()

,총사망자,총확진자,기준일,누적의심자,누적확진율,일일사망자,일일사망자2,일일사망자3
count,820.000000,8.200000e+02,8.200000e+02,6.920000e+02,623.000000,820.000000,820.000000,820.000000
mean,3927.832927,1.913097e+06,2.020897e+07,7.545057e+06,1.556435,29.574390,29.574390,29.574390
std,6164.310693,4.857030e+06,7.118265e+03,6.172020e+06,0.543014,68.530863,68.530863,68.530863
min,54.000000,7.513000e+03,2.020031e+07,2.101440e+05,0.902205,-2.000000,-2.000000,-2.000000
25%,415.750000,2.393525e+04,2.020100e+07,1.934309e+06,1.078089,2.000000,2.000000,2.000000
50%,1812.500000,1.185640e+05,2.021042e+07,6.368310e+06,1.416159,5.000000,5.000000,5.000000
75%,3120.500000,3.979915e+05,2.021112e+07,1.216890e+07,1.816009,20.000000,20.000000,20.000000
max,24305.000000,1.818820e+07,2.022061e+07,2.151807e+07,3.919308,469.000000,469.000000,469.000000

In [25]:
# 통계 정보를 확인하니 일일사망자 데이터에 음수가 확인
# 일일사망자 데이터에서 음수인 데이터를 확인하자
# 조건식 : 일일사망자 컬럼의 데이터가 0보다 작은
flag = df['일일사망자'] < 0

In [26]:
# flag는 인덱스의 조건식으로 사용이 가능
# 인덱스의 조건식을 사용하는 것은 loc
df.loc[flag, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일사망자,일일사망자2,일일사망자3
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-2,-2.0,-2.0

In [27]:
# 해당 날짜 데이터만 가지고 데이터의 문제는 발견이 힘들다. 
# +- 2일치 데이터를 확인 
df.loc[444:448, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일사망자,일일사망자2,일일사망자3
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,9733588.0,1.450884,5,5.0,5.0
445,2021-05-30 00:00:00.0,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,9761156.0,1.456805,8,8.0,8.0
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-2,-2.0,-2.0
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,9798400.0,1.455890,6,6.0,6.0
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,9834348.0,1.457668,2,2.0,2.0

In [29]:
# index 445, column은 '등록일시' 인 데이터를 변경 
df.loc[445, '등록일시'] = '2021-05-31 00:00:00.000'

In [30]:
df.loc[444:448, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일사망자,일일사망자2,일일사망자3
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,9733588.0,1.450884,5,5.0,5.0
445,2021-05-31 00:00:00.000,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,9761156.0,1.456805,8,8.0,8.0
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-2,-2.0,-2.0
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,9798400.0,1.455890,6,6.0,6.0
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,9834348.0,1.457668,2,2.0,2.0